# Настройки загрузки файлов
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=${java.io.tmpdir}

# URL для получения данных о товарах WB
wb.products.api.url=http://localhost:8080/api/wb/all-cards-mapped-short
# # Таймауты для RestTemplate
rest.template.connect-timeout=5000
rest.template.read-timeout=5000

# Настройки логирования
logging.file.name=./log/stickers.log
logging.file.path=./log
logging.pattern.level=appender
logging.charset.file=UTF-8
logging.level.root=info

# Порт сервера
server.port=8081

# Пример LDAP настроек (закомментированы)
# spring.ldap.urls=
# spring.ldap.base=
# spring.ldap.password=