name: Java CI

on:
  push:
    branches:
      - main  # Замените на имя вашей ветки, например, 'master' или 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package -DskipTests

      - name: Create ZIP archive with JAR file
        run: |
          mkdir release
          cp target/Stickers-0.0.1.jar release/
          cd release
          zip -r my-app.zip Stickers-0.0.1.jar

      - name: Upload ZIP archive to GitHub Releases
        uses: actions/upload-artifact@v3
        with:
          name: my-app-zip
          path: release/my-app.zip

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.t2 }}  # Используйте имя вашего токена
        with:
          tag_name: v1.0.1  # Замените на новый тег
          release_name: Release v1.0.1  # Замените на новое название релиза
          draft: false
          prerelease: false
          body: |
            Release notes for version 1.0.1

      - name: Upload ZIP to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.t2 }}  # Используйте имя вашего токена
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/my-app.zip
          asset_name: my-app.zip
          asset_content_type: application/zip