name: Java CI

on:
  push:
    branches:
      - main  # Замените на имя вашей ветки, например, 'master' или 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package -DskipTests

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.t2 }}  # Используйте имя вашего токена
        with:
          tag_name: v1.0.1  # Замените на новый тег
          release_name: Release v1.0.1  # Замените на новое название релиза
          draft: false
          prerelease: false
          body: |
            Release notes for version 1.0.1

      - name: Upload JAR to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.t2 }}  # Используйте имя вашего токена
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/target/Stickers-0.0.1.jar  # Используйте абсолютный путь
          asset_name: my-app.jar
          asset_content_type: application/java-archive

      - name: Delete Source Code Assets
        run: |
          curl -X DELETE -H "Authorization: token ${{ secrets.t2 }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/assets/$(curl -s -H "Authorization: token ${{ secrets.t2 }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/v1.0.1" | jq -r '.assets[] | select(.name == "Source code.zip") | .id')"
          curl -X DELETE -H "Authorization: token ${{ secrets.t2 }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/assets/$(curl -s -H "Authorization: token ${{ secrets.t2 }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/v1.0.1" | jq -r '.assets[] | select(.name == "Source code.tar.gz") | .id')"
        env:
          GITHUB_TOKEN: ${{ secrets.t2 }}  # Используйте имя вашего токена